### ISSUE TITLE
绑定接口不支持？

### ISSUE THREAD

**Issue by lonerwolf** [go-spring/go-spring#10]
已解决
RT
type EventHandler interface {
	OnNewConnect(c Connection)
	OnNewRead(c Connection, readBuffer *ringbuffer.RingBuffer)
	OnClose(c Connection)
}

type LwnetStarter struct {
	Config      *LwnetConfig       `autowire:""`
	eventHandle lwnet.EventHandler `autowire:""`
}

type LwnetServer struct {
	A int
}

func (svr *LwnetServer) OnNewConnect(c lwnet.Connection) {
	fmt.Println("OnNewConnect:" + c.RemoteAddr().String())
	a := 1
	_ = a
	return
}

func (svr *LwnetServer) OnNewRead(c lwnet.Connection, ptBuff *ringbuffer.RingBuffer) {
	fmt.Println("OnNewRead")
	a := 1
	_ = a
	tmp_buf := make([]byte, ptBuff.Length())
	ptBuff.Read(tmp_buf)
	c.Write(tmp_buf)
	return
}

func (svr *LwnetServer) OnClose(c lwnet.Connection) {
	a := 1
	_ = a
	fmt.Println("OnClose")
	return
}

这样注册这个BEAN，无法自动绑定，
错误panic: reflect: reflect.flag.mustBeAssignable using value obtained using unexported field

**Comment by lvan100** [comment]
😆
