### ISSUE TITLE
希望暴露gs.getProperty(key), 刷新bean方法

### ISSUE THREAD

**Issue by zundaren** [go-spring/go-spring#105]

**Comment by zundaren** [comment]
特殊情况需要手动刷新bean内部属性值

**Comment by lvan100** [comment]
为什么呢？属性绑定的方式不能满足么？可以详细讲一下特殊性么？

**Comment by zundaren** [comment]
> 为什么呢？属性绑定的方式不能满足么？可以详细讲一下特殊性么？

一个简单的工具类想获取属性值还要再建个结构体绑定，太啰嗦了，就是希望便捷的取值，如果是获取大批量的属性肯定还是绑定方便啊。属性如果是通过数据库等方式设置进去的，改动属性后刷新bean的值，这个也有个别情况需要手动控制

**Comment by lvan100** [comment]
> > 为什么呢？属性绑定的方式不能满足么？可以详细讲一下特殊性么？
> 
> 一个简单的工具类想获取属性值还要再建个结构体绑定，太啰嗦了，就是希望便捷的取值，如果是获取大批量的属性肯定还是绑定方便啊。属性如果是通过数据库等方式设置进去的，改动属性后刷新bean的值，这个也有个别情况需要手动控制

这件事情我是这么想的。第一，现在的 IoC 核心是基于 map 的，这意味着运行时修改会有并发风险，也就是说，现在的 IoC 是一个只读的容器，不能在运行时修改它的任何东西，包括属性和 Bean，这个是现在设计的原则和取舍。第二，因为 IoC 是只读的，所以属性和 Bean 的获取必须在启动阶段完成，这时候可以使用 gs.Context 提供的方法获取属性和 Bean，gs 支持启动阶段任何地方注入和使用 gs.Context 对象。第三，建议对可变的属性进行单独管理，后续这块也可能会有单独的 API 实现，但是很可能大家在如何动态配置这块有不同的想法和基础设施，所以现阶段还是由大家自行决策这块的实现。

**Comment by zundaren** [comment]
> > > 为什么呢？属性绑定的方式不能满足么？可以详细讲一下特殊性么？
> > 
> > 
> > 一个简单的工具类想获取属性值还要再建个结构体绑定，太啰嗦了，就是希望便捷的取值，如果是获取大批量的属性肯定还是绑定方便啊。属性如果是通过数据库等方式设置进去的，改动属性后刷新bean的值，这个也有个别情况需要手动控制
> 
> 这件事情我是这么想的。第一，现在的 IoC 核心是基于 map 的，这意味着运行时修改会有并发风险，也就是说，现在的 IoC 是一个只读的容器，不能在运行时修改它的任何东西，包括属性和 Bean，这个是现在设计的原则和取舍。第二，因为 IoC 是只读的，所以属性和 Bean 的获取必须在启动阶段完成，这时候可以使用 gs.Context 提供的方法获取属性和 Bean，gs 支持启动阶段任何地方注入和使用 gs.Context 对象。第三，建议对可变的属性进行单独管理，后续这块也可能会有单独的 API 实现，但是很可能大家在如何动态配置这块有不同的想法和基础设施，所以现阶段还是由大家自行决策这块的实现。

动态属性可以参考springcloud里面的方式，我现在拿到map,修改map加锁就完事了，我覆盖map里面的值，一般改的都是配置文件里面的属性，然后发送一个刷新事件，gs监听刷新事件，怎么刷新不管，用户只需要含有最新属性的bean就行了

**Comment by lvan100** [comment]
> 动态属性可以参考springcloud里面的方式，我现在拿到map,修改map加锁就完事了，我覆盖map里面的值，一般改的都是配置文件里面的属性，然后发送一个刷新事件，gs监听刷新事件，怎么刷新不管，用户只需要含有最新属性的bean就行了

你的意思我明白，方案也是可行的，但是看起来不够 IoC，可以和 IoC深度结合一下么？

**Comment by lvan100** [comment]
这件事情在最新版里给出了答案：go-spring 只提供用于注册各种信息的写方法，不会提供任何形式的读方法。

但是怎么获取ioc里面的数据呢？答案是使用 gs.ContextAware。下面是它的一个示例。

![2d49f593cc1e462c.jpg](https://user-images.githubusercontent.com/9102784/182159714-9f4c95e0-0f3d-4342-9530-75073e24dbfd.jpg)

**Comment by zundaren** [comment]
> 这件事情在最新版里给出了答案：go-spring 只提供用于注册各种信息的写方法，不会提供任何形式的读方法。
> 
> 但是怎么获取ioc里面的数据呢？答案是使用 gs.ContextAware。下面是它的一个示例。
> 
> ![2d49f593cc1e462c.jpg](https://user-images.githubusercontent.com/9102784/182159714-9f4c95e0-0f3d-4342-9530-75073e24dbfd.jpg)
> 
> 这种方式同时会促进 struct 封装，更容易写出更模块化的程序。

也行吧这样，那动态配置现在要怎么搞，配置中心就做不了了
