### ISSUE TITLE
1.0.0 al版本无法初始化获取配置如何解决

### ISSUE THREAD

**Issue by lonerwolf** [go-spring/go-spring#13]
原来的
SpringBoot.RegisterModule(func(ctx SpringCore.SpringContext) {
		tmp := new(Gorm)
		var err error
		databaseType, ok := ctx.GetDefaultProperty("gorm.database", "postgres")
		if !ok {

		}
tmp.DB, err = gorm.Open(databaseType.(string), conn_str)
		if err != nil {
			panic(err)
		}
		ctx.RegisterBean(tmp)

现在
init里面无法获取配置SpringBoot.RegisterBean(redisClient)。
因为想在SPRING注册里面实现加载配置测试连接是否成功

**Comment by lvan100** [comment]
你好，你的意思是在module里面没法获取其他地方注册的bean吧？module机制是存在这个问题的，它解决不了模块之间存在依赖的问题，只能手动安排好import的顺序。我建议你升级到最新版本，增加了非常多的功能。然后可以加一下QQ群能获取到及时的解答。

**Comment by lonerwolf** [comment]
> 你好，你的意思是在module里面没法获取其他地方注册的bean吧？module机制是存在这个问题的，它解决不了模块之间存在依赖的问题，只能手动安排好import的顺序。我建议你升级到最新版本，增加了非常多的功能。然后可以加一下QQ群能获取到及时的解答。

可以了，用了构造函数注册，在构造函数里面手动获取配置

**Comment by lvan100** [comment]
赞！
