### ISSUE TITLE
go-spring 1.1.3无法读取配置文件

### ISSUE THREAD

**Issue by packyzhou** [go-spring/go-spring#132]
```
fmt.Println("初始化")
	gs.Setenv("INCLUDE_ENV_PATTERNS", "GOPATH")
	gs.Setenv("GS_SPRING_PROFILES_ACTIVE", "")
	gs.Setenv("GS_SPRING_CONFIG_LOCATIONS", "config/")
	gs.Setenv("GS_SPRING_CONFIG_EXTENSIONS", ".properties,.prop,.yaml,.yml,.toml,.tml,.ini")

```

├── config
│   ├── aplication-dev.yml
│   ├── aplication-test.yml
│   └── aplication.yml
├── go.mod
├── go.sum
├── main.go
└── vendor
    ├── github.com
    ├── golang.org
    ├── gopkg.in
    └── modules.txt

为什么我设置了环境变量，但是gs.Run()并没有读取配置文件

**Comment by lvan100** [comment]
多谢关注，单词拼错喽

**Comment by packyzhou** [comment]
> 多谢关注，单词拼错喽

谢谢，已经解决
