### ISSUE TITLE
怎样渲染html 

### ISSUE THREAD

**Issue by mullerhai** [go-spring/go-spring#16]
我现在使用
	ctx.Stream(http.StatusOK,"html",htmlfile)，发现其中html 引用的css 文件加载不了
有没有更友好的方式呢，也可以使用ctx.File() ,但是一样 引用的css 加载不到，有没有类似

我发现 好像go spring 底层的gin 的问题
https://stackoverflow.com/questions/36237060/gin-golang-loading-html-files-with-stylesheet

**Comment by lvan100** [comment]
是不是go-spring升级一下gin的版本就能解决呢？

**Comment by mullerhai** [comment]
> 是不是go-spring升级一下gin的版本就能解决呢？

是其引用的gin 的版本太低吗
