### ISSUE TITLE
您好，关于注解的Demo在哪里

### ISSUE THREAD

**Issue by GuoxinL** [go-spring/go-spring#19]
如题，您好，关于注解的Demo在哪里

**Comment by lvan100** [comment]
https://github.com/go-spring/go-spring/blob/master/spring-boot/spring-boot_test.go
另外，Go 是没有注解的，文档里面的意思是 Go-Spring 实现了 Java Spring 注解的功能，有些是通过 Tag 实现的，更多的是通过函数实现的。请参考上面的示例。
