### ISSUE TITLE
自定义类实现 Context 接口的话，有效率问题

### ISSUE THREAD

**Issue by xy-github-issue** [go-spring/go-spring#20]
官方的 context 包里有个 propagateCancel ，这里的逻辑是：
如果是 官方的几个context 类，那么直接找子节点做cancel
如果是 自定义的类，那么起个协程去做

SpringContext 嵌着一个 context.Context，但是，如果真的当作 context.Context 来用，代价是很高的，有考虑过这个问题吗？

**Comment by lvan100** [comment]
这个还真不知道，你有好的方案吗？

**Comment by Greastate** [comment]
> 这个还真不知道，你有好的方案吗？

全局只应通用context.Context，不要另外定义context，如果要存放数据，通过withValue即可，要设置超时时长通过withTimeout或withDeadline，这是go的标准做法

**Comment by lvan100** [comment]
不知道是不是你理解错了，使用的就是标准 context.Context，看下面的源码，

```
// defaultSpringContext SpringContext 的默认版本
type defaultSpringContext struct {
	// 上下文接口
	context.Context
	cancel context.CancelFunc
        ...
}

// NewDefaultSpringContext defaultSpringContext 的构造函数
func NewDefaultSpringContext() *defaultSpringContext {
	ctx, cancel := context.WithCancel(context.Background())
	return &defaultSpringContext{
		Context:         ctx,
		cancel:          cancel,
                 ...
	}
}
```

**Comment by xy-github-issue** [comment]
> 不知道是不是你理解错了，使用的就是标准 context.Context，看下面的源码，
> 
> ```
> // defaultSpringContext SpringContext 的默认版本
> type defaultSpringContext struct {
> 	// 上下文接口
> 	context.Context
> 	cancel context.CancelFunc
>         ...
> }
> 
> // NewDefaultSpringContext defaultSpringContext 的构造函数
> func NewDefaultSpringContext() *defaultSpringContext {
> 	ctx, cancel := context.WithCancel(context.Background())
> 	return &defaultSpringContext{
> 		Context:         ctx,
> 		cancel:          cancel,
>                  ...
> 	}
> }
> ```

这个是回我的？还是回 Greastate 的？

我也解释一下我的担心吧：
结构体  defaultSpringContext 是可以嵌一个 context.Context，
而且 defaultSpringContext 已经可以作为 context.Context 用了，但是呢，这样是有性能问题的，官方包认不出 defaultSpringContext 结构，哪性内嵌的 context.Context  是官方的。
除非在使用时， 不是把 defaultSpringContext 用做 context.Context ，而且用 defaultSpringContext.Context。**defaultSpringContext 和 defaultSpringContext.Context 是有区别的。**
 
而 SpringContext 是一个接口，内嵌了一个 context.Context，不存在用官方的几个 context.Context 类去实现它的可能了，实现了 SpringContext 的类，如果做为 context.Context 接口用，必然会被  propagateCancel 当作第三方类来处理的。

**Comment by lvan100** [comment]
嗯嗯，明白了。

**Comment by lvan100** [comment]
> 官方的 context 包里有个 propagateCancel ，这里的逻辑是：
> 如果是 官方的几个context 类，那么直接找子节点做cancel
> 如果是 自定义的类，那么起个协程去做
> 
> SpringContext 嵌着一个 context.Context，但是，如果真的当作 context.Context 来用，代价是很高的，有考虑过这个问题吗？

目前改成提供 Context()context.Context 函数可以解决你说的这个问题吗？
