### ISSUE TITLE
Ioc

### ISSUE THREAD

**Issue by yz-java** [go-spring/go-spring#27]
spring使用Java注解扫描包完成bean定义、初始化、实例化、注册一系列操作；使用golang的哪个特性可以完成扫描那一步的操作？

**Comment by lvan100** [comment]
1. 匿名包导入可替代扫描机制，java 是半自动，go 是纯手动；
2. 在 init 函数里面用 register 系列函数注册元数据可替代部分注解的功能，比如 condition 系列注解；
3. tag 机制也可替代一部分注解的功能，比如 @autowired 和 @value。
