### ISSUE TITLE
Http response status与日志记录的err code及描述不一致

### ISSUE THREAD

**Issue by tcxiaotudou** [go-spring/go-spring#44]
- Version.

  `v1.0.5`

- Logs.

  ```bash
  [ERROR] spring-web@v1.0.5/spring-web-container.go:322 [PANIC RECOVER] code=404, message=Not Found
  ```

- Screenshots.

![36P5QM$ DM$5L0$F5YB}WJU](https://user-images.githubusercontent.com/17454614/95822757-188ed480-0d5f-11eb-99f2-da920ee5045e.png)

- Steps to reproduce the issue.

  当访问的路由不存在时，http response status为500，但日志记录为404，not found，两者不统一。

**Comment by lvan100** [comment]
新版本已经解决了。
