### ISSUE TITLE
关于 golint 报名警告

### ISSUE THREAD

**Issue by ravenq** [go-spring/go-spring#45]
Effective Go 包命名规则：

https://golang.google.cn/doc/effective_go.html#package-names

![图片](https://user-images.githubusercontent.com/8143686/97103004-00b33b00-16e5-11eb-9eb8-2dee0646ebc8.png)

是否考虑换下报名？ 直接 springboot ?

**Comment by lvan100** [comment]
正如 https://github.com/go-spring/go-spring/issues/18 中我所回复的那样，采用大写开头的包名也是从美观的角度出发的。
