### ISSUE TITLE
go 1.15用官网示例，直接报错了。

### ISSUE THREAD

**Issue by dk333** [go-spring/go-spring#49]
go 1.15用官网示例，直接报错了。

> E:\workspace\go\learn-go-spring>go run server.go
> go: finding module for package github.com/go-spring/starter-echo
> go: finding module for package github.com/go-spring/spring-boot
> go: found github.com/go-spring/spring-boot in github.com/go-spring/spring-boot v1.0.5
> go: found github.com/go-spring/starter-echo in github.com/go-spring/starter-echo v1.0.5
> 
>  _______  _______         _______  _______  _______ _________ _        _______
> (  ____ \(  ___  )       (  ____ \(  ____ )(  ____ )\__   __/( (    /|(  ____ \
> | (    \/| (   ) |       | (    \/| (    )|| (    )|   ) (   |  \  ( || (    \/
> | |      | |   | | _____ | (_____ | (____)|| (____)|   | |   |   \ | || |
> | | ____ | |   | |(_____)(_____  )|  _____)|     __)   | |   | (\ \) || | ____
> | | \_  )| |   | |             ) || (      | (\ (      | |   | | \   || | \_  )
> | (___) || (___) |       /\____) || )      | ) \ \_____) (___| )  \  || (___) |
> (_______)(_______)       \_______)|/       |/   \__/\_______/|/    )_)(_______)
> 
>                    go-spring@v1.0.5    http://go-spring.com/
> 
> [ERROR] spring-core@v1.0.5/spring-context-default.go:617 fn should be func(context.Context, *struct})anything ↩
> => object bean "*main.Echo" E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-bean.go:841 ↩
> panic: fn should be func(context.Context, *struct})anything [recovered]
>         panic: fn should be func(context.Context, *struct})anything
> 
> goroutine 1 [running]:
> github.com/go-spring/spring-core.(*defaultSpringContext).AutoWireBeans.func1(0xc000bfd1a0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-context-default.go:618 +0x168
> panic(0x18d3700, 0xc000c70eb0)
>         D:/Go/src/runtime/panic.go:969 +0x176
> github.com/go-spring/spring-web.BIND(0x18ae060, 0xc000c70ea0, 0x0, 0xc000bfd220)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-web@v1.0.5/spring-web-rpc.go:87 +0x2d1
> github.com/go-spring/spring-boot.GetBinding(0x1997146, 0x1, 0x18ae060, 0xc000c70ea0, 0x0, 0x0, 0x0, 0x18b1a20)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-boot@v1.0.5/spring-boot-web.go:423 +0x45
> main.init.0.func1(0xc000c2fb40)
>         E:/workspace/go/learn-go-spring/server.go:10 +0x94
> reflect.Value.call(0x18ae920, 0x19caf00, 0x13, 0x1997c1f, 0x4, 0xc000bfd1e0, 0x1, 0x1, 0x1, 0x0, ...)
>         D:/Go/src/reflect/value.go:475 +0x8e7
> reflect.Value.Call(0x18ae920, 0x19caf00, 0x13, 0xc000bfd1e0, 0x1, 0x1, 0x0, 0x0, 0xc000c2fb40)
>         D:/Go/src/reflect/value.go:336 +0xc5
> github.com/go-spring/spring-core.(*runnable).run(0xc00004c480, 0xc000bfd1a0, 0xc000bfab80, 0x0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-configer.go:65 +0x1ee
> github.com/go-spring/spring-core.(*defaultBeanAssembly).wireBeanDefinition(0xc000bfd1a0, 0x1a7f0c0, 0xc000bfab80, 0x26f1b00)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-bean-assembly.go:442 +0x6db
> github.com/go-spring/spring-core.(*defaultSpringContext).wireBeans(0xc000d205a0, 0xc000bfd1a0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-context-default.go:594 +0xc5
> github.com/go-spring/spring-core.(*defaultSpringContext).AutoWireBeans(0xc000d205a0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-core@v1.0.5/spring-context-default.go:623 +0x192
> github.com/go-spring/spring-boot.(*application).Start(0xc000b005a0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-boot@v1.0.5/spring-boot-app.go:131 +0x15e
> github.com/go-spring/boot-starter.Run(0x1a6e7e0, 0xc000b005a0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/boot-starter@v0.0.0-20200808142234-b000c10161b2/boot-starter.go:47 +0x86
> github.com/go-spring/spring-boot.(*AppBuilder).Run(0xc000e1ff78, 0x0, 0x0, 0x0)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-boot@v1.0.5/spring-boot-singlet.go:67 +0x20b
> github.com/go-spring/spring-boot.RunApplication(...)
>         E:/GOPATH/pkg/mod/github.com/go-spring/spring-boot@v1.0.5/spring-boot-singlet.go:72
> main.main()
>         E:/workspace/go/learn-go-spring/server.go:23 +0x45
> exit status 2

**Comment by yubingex007-a11y** [comment]
I encountered this issue as well. should I roll back to go1.12?

**Comment by lvan100** [comment]
官网示例已更新。
