### ISSUE TITLE
能否将controller中的路由通过swagger扫描自动加入到Route中

### ISSUE THREAD

**Issue by ghchris** [go-spring/go-spring#56]
`
//菜单
type TestController struct {
}

// @Title 	获取所有菜单
// @Description 	获取所有菜单
// @Param	U-Token		header 	string	true "header.token"
// @Param   meta_title path  string false		"菜单名称"
// @Success 200 {object} model.JsonReturn
// @Failure 403 {string} string 查询错误
// @Router /a [get]
func (c *TestController) GetAll(ctx SpringWeb.WebContext) {
	ctx.JSON(200,model.JsonReturn{Name:"test"})
}

// @Title 	获取所有菜单
// @Description 	获取所有菜单
// @Param	body	body 	model.TestModel	true 	"菜单体"
// @Success 200 {object} model.JsonReturn
// @Failure 403 {string} string 查询错误
// @Router /b [get]
func (c *TestController) GetOne(ctx SpringWeb.WebContext) {
	ctx.JSON(200,model.JsonReturn{Name:"test"})
}`

`v1 := SpringBoot.Route("/api", &filter.ApiFilter{}).Route("/v1")
v1.HandleController(&controller.TestController{})`

类似这种通过controller对象扫描所有的路由

**Comment by lvan100** [comment]
启动过程中扫描的方案是不可行的，需要在编译前使用工具扫描，生成代码，然后启动过程中执行这些代码。

**Comment by ghchris** [comment]
为什么呢！ 能帮忙解答一下吗？谢谢

**Comment by lvan100** [comment]
> 为什么呢！ 能帮忙解答一下吗？谢谢

通过某种规则扫描 controller 里面的方法然后注册是可以实现的，肯定也有其他框架已经实现了，限定只扫描哪些方法很容易，但是路由地址怎么映射很麻烦，下划线风格还是驼峰风格，如果是驼峰，那是全驼峰还是第一个字母小写的驼峰，这些规则无论是记忆还是使用都很不容易。
所以我更倾向于代码生成工具的方案，用户可以把路由的元数据用注释写出来，代码生成工具扫描然后生成和手写一样的路由注册代码。
另外，问题试图给出的解决方案并不是一种通用方案，实现了怕也是鸡肋。

**Comment by ghchris** [comment]
好的！学习了！谢谢
