### ISSUE TITLE
有木有WEB中间件范例

### ISSUE THREAD

**Issue by lonerwolf** [go-spring/go-spring#6]
比如拿现成继承的例子

**Comment by lvan100** [comment]
`
package main

import (
	"fmt"

	_ "github.com/go-spring/demo-web/example"
	_ "github.com/go-spring/go-spring-boot-starter/starter-echo"
	_ "github.com/go-spring/go-spring-boot-starter/starter-web"
	"github.com/go-spring/go-spring-boot/spring-boot"
	"github.com/go-spring/go-spring/spring-core"
	"github.com/go-spring/go-spring/spring-echo"
	"github.com/labstack/echo"
	"github.com/labstack/echo/middleware"
)

//
// 注册 echo 容器
//
func registerEchoContainer() {
	SpringBoot.RegisterModule(func(ctx SpringCore.SpringContext) {

		e := echo.New()
		e.HideBanner = true
		e.Use(middleware.Recover())

		e.Use(func(next echo.HandlerFunc) echo.HandlerFunc {
			return func(c echo.Context) error {
				fmt.Println("use registerEchoContainer()")
				return next(c)
			}
		})

		c := &SpringEcho.Container{
			EchoServer: e,
		}

		ctx.RegisterNameBean("WebContainer", c)
	})
}

func main() {
	if false {
		registerEchoContainer()
	}
	SpringBoot.RunApplication("config/")
}
`

目前 go-spring-web 有两种中间件，一种基于 web 容器自身的能力，如上所示，通过注入一个用户自定义的 web 容器来实现；另一种是基于 web 路由注册时的 filter 能力。两种方式可以同时使用。
