### ISSUE TITLE
发展计划

### ISSUE THREAD

**Issue by FourSpaces** [go-spring/go-spring#72]
有制订开发计划么？想了解一下，后续的发展方向

**Comment by lvan100** [comment]
框架后面不会大改了，IoC 实现基本稳定，后面也就是修修补补，Web 模块还需打磨，继续完善，但是主体框架不会大改。后面会继续发力 Redis、MQ 、MySQL 标准化，22 年能把上面几个模块打磨好就算实现目标了。另外，22 年打算出海，加大推广力度。

**Comment by lkqm** [comment]
关于项目的可靠性怎么样？关注go-spring一年多了，但是没有看到文档中提及 是否有在生产中大量使用、谁在使用、性能怎么样

**Comment by lvan100** [comment]
目前没有大型项目使用的案例，基本都是非核心项目在实验性使用。go-spring 目前发布了一个比较完善的 1.0.5 版本，提供了基础的 ioc 能力。最新开发的是 1.1.0 版本，但是还没有正式 release ，原因是 1.1.0 版本想要提供一个更加完整的框架，把我最近一年的实践添加进去，并且从长远来看，为模块的封装提供更加准确的范例，争取一次就把事情做好。如果用户太多，api 变化频繁的话估计要被骂死了，所以有个大方向，具体什么时候能完成，没有具体的时间点。
