### ISSUE TITLE
支持使用状态码吗，去掉`{"code":200,"msg":"SUCCESS","data":"ok"}这一层包装

### ISSUE THREAD

**Issue by wxq851685279** [go-spring/go-spring#74]
spring 可以使用ResponseEntity配置状态码，或者@ResponseStatus注解配置返回的状态码，做统一异常处理，
对于2xx状态码的不需要{"code":200,"msg":"SUCCESS","data":"ok"}这一层，只有不是2xx才需要返回

**Comment by wxq851685279** [comment]
@lvan100 ？？支持吗

**Comment by lvan100** [comment]
不支持，之前确实这样，但是不小心出了 bug，所以就不那么搞了，可以参考 https://github.com/go-spring/go-spring/blob/master/examples/spring-boot-web/main.go
