### ISSUE TITLE
Go-Spring 核心原理 (上) 一文中

### ISSUE THREAD

**Issue by zhangkyou** [go-spring/go-spring#8]
func main() {
 
   springContext := **SpringCore.NewSpringContext()**
 
   app := new(Application)
   springContext.RegisterBean(app)
 
   cfg := &Config{Name: "Jim"}
   springContext.RegisterBean(cfg)
 
   ds := &DataSource{
      Url: "jdbc:mysql:127.0.0.1...",
   }
 
   springContext.RegisterBean(ds)
   //springContext.RegisterNameBean("ds", ds) // 这一行!
 
   springContext.AutoWireBeans()
 
   b, _ := json.MarshalIndent(app, "", "  ")
   fmt.Println(string(b))
}

SpringCore包没有这个NewSpringContext()方法

**Comment by lvan100** [comment]
那篇文章写出来就已经过时了，但基本原理不变，😂，请关注最新的代码实现吧
