### ISSUE TITLE
关于模块全在一个项目下的问题

### ISSUE THREAD

**Issue by LINGLUOJUN** [go-spring/go-spring#86]
go-spring 里面是否考虑把各核心包拆分成多个项目,就现有的在一个项目里面对于开发者来说不是那么有好

**Comment by lvan100** [comment]
嗯，能列举一二么？因为现有管理模式也是摸索出来的。

**Comment by l4dfire** [comment]
> 嗯，能列举一二么？因为现有管理模式也是摸索出来的。

我第一反应，go-spring 应该是一个 group name ，而不是一个 project name.
其下会有 go-spring-ioc, go-spring-web, go-spring-redis .. 诸如此类
而 go-spring-core 来提供插拔功能, java-spring group 如下:

https://github.com/orgs/spring-projects/repositories?page=7&type=all

现在这样冒昧地说，确实太大了。

**Comment by lvan100** [comment]
> > 嗯，能列举一二么？因为现有管理模式也是摸索出来的。
> 
> 我第一反应，go-spring 应该是一个 group name ，而不是一个 project name.
> 其下会有 go-spring-ioc, go-spring-web, go-spring-redis .. 诸如此类
> 而 go-spring-core 来提供插拔功能, java-spring group 如下:
> 
> https://github.com/orgs/spring-projects/repositories?page=7&type=all
> 
> 现在这样冒昧地说，确实太大了。

现在就是这样的，go-spring 是一个组织，包含 go-spring/spring-core、go-spring/spring-gin 这样独立的项目，它们是最终给用户使用的，而 go-spring/go-spring 是一个为了方便开发建立的大仓库，平常我们在 go-spring/go-spring 项目上开发，有点类似于 go 最新推出的 workspace，发版的时候使用工具把各个项目的代码推送到 spring-gin 这些独立项目上。
go-spring 这样做当然也是有原因的。 go sdk 可以在各个分项目上开发，然后进行代码合并发版。go-spring 和它是反着的，在一个主项目上开发，然后推送到各个子项目上。和 java spring 本质上也是一样的。

**Comment by l4dfire** [comment]
> 

😂 原来如此，多谢指点，拙见可以在 readme 上加个说明下子项目所在。
