### ISSUE TITLE
官网给的例子根本没法跑起来！！！

### ISSUE THREAD

**Issue by zouzg** [go-spring/go-spring#87]
其中import中
```
_ "github.com/go-spring/go-spring/starter-echo"
```
根本找不到，我改成到是可以编译通过了
```
_ "github.com/go-spring/starter-echo"
```

官网地址：http://go-spring.com/en-us/docs/user/quick-start.html

**Comment by lvan100** [comment]
不好意思啦，官网的内容很久没更新了

**Comment by acrossmountain** [comment]
> 其中import中
> 
> ```
> _ "github.com/go-spring/go-spring/starter-echo"
> ```
> 
> 根本找不到，我改成到是可以编译通过了
> 
> ```
> _ "github.com/go-spring/starter-echo"
> ```
> 
> 官网地址：http://go-spring.com/en-us/docs/user/quick-start.html

仓库的 readme 提供有基础入门案例 ↓
https://github.com/go-spring/go-spring#%E5%BF%AB%E9%80%9F%E7%A4%BA%E4%BE%8B
