### ISSUE TITLE
能否考虑将 checkCondition 从 autoWireBeans 抽到 register 中

### ISSUE THREAD

**Issue by l4dfire** [go-spring/go-spring#88]
比如某两个 bean 的存在根据某些条件互斥， 但必定存在其中一个。 
同是又存在同类型的其他 bean 导致无法按类型注入。
这时候注册两个**同名同类型且存在条件互斥**的 bean 应该是合理的

假设一场景：
生产环境 redis 分为持久化集群与非持久化集群， 但测试环境仅有一套。
有 demo 如下:
```golang
type Service struct {
	RedisStore *Redis `autowire:"storeRedis"` //持久化集群, primary
	RedisCache *Redis `autowire:"cacheRedis"` // 仅缓存集群
}
func main() {
	context := SpringCore.DefaultApplicationContext()
	testEnvCondition := SpringCore.NewPropertyValueCondition("env", "testing")
	context.RegisterBeanDefinition(
		SpringCore.ObjectBean(NewStoreRedis).Primary(true).
			// 正式环境可用 持久化 集群
			ConditionNot(testEnvCondition).
			WithName("storeRedis"))
	context.RegisterBeanDefinition(
		// 测试环境 持久化集群不可用, 业务逻辑上使用个壳子替代其 bean 定义
		SpringCore.ObjectBean(NewFakeRedis).Primary(true).
			ConditionNot(testEnvCondition).
                        //但是要求同名
			WithName("storeRedis"))
	context.RegisterNameBeanFn("cacheRedis", NewCacheRedis)
}
```

目前这段是肯定会报 「duplicate registration」，如果能将 checkCondition 提取到注册时, 不满足直接不注册了就会舒服很多。

我理解当初这么设计可能是因为没有把启动流程控死， 可能是 SetProperty 和 RegisterBean 这两块没有严格顺序?
是否有希望可以调整呢?

**Comment by lvan100** [comment]
condition 不能立即计算出来，因为可能会依赖其他 bean 的信息，或者依赖的属性还没准备好。

**Comment by lvan100** [comment]
你可能要再熟悉熟悉依赖注入的用法，我觉得你说的这种情况应该使用配置来解决，正常情况下测试环境一套配置，线上环境一套测试，因此可以使用一个属性控制 storeredis 是否创建。

**Comment by l4dfire** [comment]
> 你可能要再熟悉熟悉依赖注入的用法，我觉得你说的这种情况应该使用配置来解决，正常情况下测试环境一套配置，线上环境一套测试，因此可以使用一个属性控制 storeredis 是否创建。

是的，一个两个确实可以在测试环境使用同样的配置来解决。 现在也确实这么做的。
我这个例子不太恰当， 引起误解请见谅。

还是换个说法，抽象点说两个或者以上 bean 互斥同名的bean , 最终在实际运行上只会有唯一一个叫这个名字的 bean。
我如果有多种这样的场景，比如 条件链，逻辑树 这种 bean  group , 我更希望能通过少数几个配置项来决定最终生成的 group 结构. 
而不是将每个 bean 的配置都写到 配置文件。

写这我发现，我希望的更多是可以通过配置来完成逻辑切换， 而不止通过配置去影响资源切换。
配置通过 condition 来体现，而逻辑由存在的 bean 的内部完成。

之前也希望通过  ConditionOnMissingBean 来实现个别场景，奈何是同样的原因。 
```golang
func main() {
	appCtx := SpringCore.DefaultApplicationContext()
	appCtx.RegisterBeanDefinition(
		SpringCore.ObjectBean(NewA).ConditionOn(some condition))
	appCtx.RegisterBeanDefinition(
		SpringCore.ObjectBean(NewA).ConditionOnMissingBean((*A)(nil)))
}
```
然而 java-spring 其实可以支持这种场景

```java
@SpringBootConfiguration
public class AConfiguration {

    @Bean
    public A a() {
        return new A();
    }
}
```
```java
@SpringBootConfiguration
public class BConfiguration {

    @Bean
    @ConditionalOnMissingBean
    public A a() {
        return new A();
    }
}
```

> condition 不能立即计算出来，因为可能会依赖其他 bean 的信息，或者依赖的属性还没准备好。

那么，可否换个角度想，是否可以允许同名的 definition , 而不允许同名的 beanCacheItem 呢? 

实际上 java-spring 也是这么做的，他在 ConfigurationClassBeanDefinitionReader 会对 definition 做过滤, 来决定哪些 definition 可以通过校验.

**Comment by lvan100** [comment]
谢谢！实际上注册的时候不允许同名同类型是我特意为之的，因为我觉得一是将重复检测放到 bean 决策阶段太晚了，二是如果允许了我没有看到有什么好处，甚至应该促使开发者去思考为何出现此种情况。
当然如果有正当合理的理由促使我们必须将重复检测放到决策阶段也是可以改的。😄

**Comment by lvan100** [comment]
@l4dfire 和你的讨论给了我一个新的想法，也许 go-spring 可以引进 configuration 的概念，可以认为它是一个配置组，配置组之间可以有互斥关系，不同的配置组之间可以有同名同类型的 bean。在现有的 bean 决策阶段之前增加一个 configuration 决策和配置展开即可。不过我得先想想它的必要性。

**Comment by lvan100** [comment]
> @l4dfire 和你的讨论给了我一个新的想法，也许 go-spring 可以引进 configuration 的概念，可以认为它是一个配置组，配置组之间可以有互斥关系，不同的配置组之间可以有同名同类型的 bean。在现有的 bean 决策阶段之前增加一个 configuration 决策和配置展开即可。不过我得先想想它的必要性。

我想了下，应该没有必要。Java Spring 的 @Configuration 注解有 bean group 的含义，但更重要的是有其特殊含义。回到 bean group 上来，如果需要给 bean group 添加一个限制的话，最有可能的是使用属性，而 go-spring 的 onproperty 方法首先可以获取到属性值，然后是可以注册一组 bean，因此，onproperty 方法完全可以代替这里 configuration 的概念。

**Comment by l4dfire** [comment]
> > @l4dfire 和你的讨论给了我一个新的想法，也许 go-spring 可以引进 configuration 的概念，可以认为它是一个配置组，配置组之间可以有互斥关系，不同的配置组之间可以有同名同类型的 bean。在现有的 bean 决策阶段之前增加一个 configuration 决策和配置展开即可。不过我得先想想它的必要性。
> 
> 我想了下，应该没有必要。Java Spring 的 @configuration 注解有 bean group 的含义，但更重要的是有其特殊含义。回到 bean group 上来，如果需要给 bean group 添加一个限制的话，最有可能的是使用属性，而 go-spring 的 onproperty 方法首先可以获取到属性值，然后是可以注册一组 bean，因此，onproperty 方法完全可以代替这里 configuration 的概念。

感谢节日回复，幸苦了。

我刚尝试了您说的 group 方法，其本质是把 condition 使用 Properties 的计算逻辑在项目启动逻辑中放到了注册 bean 之前。
确实可行，是我对使用 go-spring 了解不够，感谢建议。
不过如此，就可惜 conditional 似乎有点意义不大了。
