### ISSUE TITLE
关于XxxMapping方法和XxxBinding方法合并

### ISSUE THREAD

**Issue by lkqm** [go-spring/go-spring#93]
在使用XxxBinding过程中发现这个方法限制比较多（2个入参，1个返回参数）, 查看源码发现XxxMapping可以和XxxBinding合并:

router.go

原方法:
```golang
func (r *router) RequestMapping(method uint32, path string, fn HandlerFunc) *Mapper {
	return r.request(method, path, FUNC(fn))
}
```

修改后:
```golang
func (r *router) RequestMapping(method uint32, path string, fn interface{}) *Mapper {
	var handler Handler
	if f, ok := fn.(func(ctx web.Context)); ok {
		handler = FUNC(f)
	} else if f, ok := fn.(func(http.ResponseWriter, *http.Request)); ok {
		var hf http.HandlerFunc = f
		handler = httpFuncHandler(hf)
	} else {
		handler = BIND(fn)
	}
	return r.request(method, path, handler)
}

```

另外XxxBinding的处理方法限制条件有些多, 参数和返回值尽可能宽松，这样才能符合使用习惯

**Comment by lvan100** [comment]
每种方式都有单独的函数是考虑到使用编译期检查，肯定是利大于弊的，记一遍几个函数也就知道怎么用了，使用起来应该挺方便的。而 binding 的限制应该说比较少了，强制的 ctx，加一个输入一个输出，最基本的限制了。后面binding 模式可以和静态代码生成 idl 技术合作，易用性能更好。

**Comment by lkqm** [comment]
控制层接口方法编译检查似乎不是很重要，可以考虑把选择权交给开发者，同时减少了一个api接口开发者更简单，目前在把一个玩具项目用go-spring来实现，有的接口方法 有绑定参数但是没有返回值，有的接口方法有返回值没有绑定参数，这样XxxBinding就无法使用了，如下：
```
gs.GetMapping("/api/projects", GetProjects)
gs.PostMapping("/api/projects", CreateProject)

// 获取项目列表
func GetProjects(ctx web.Context) []Project() {
	
}


// 创建项目
func CreateProject(ctx web.Context, request *CreateProjectRequest) {
	
}
```

**Comment by lvan100** [comment]
嗯，你上面提到的这种情况确实存在，但是从项目管理的角度来看，我们期望所有的接口签名能保持一致的格式，即使对于没有输入或者输出参数的情况，也倾向于给一个占位的参数，也方便后续扩展。甚至，你可能也听说过，有些公司要求所有的后端 http 请求只能使用 post 方法，也是一样的道理。

另外，你上面的例子里面存在使用错误，或者是笔误。Handle* 和 *Mapping 的关系就像标准库里面 Handle 和 HandleFunc 关系一样，一个面向接口，一个是接口的 func 版本。*Binding 是 *Mapping 的特殊约定版本。其实无论哪种形式，函数的参数里面都包含了三个要素，串联链路和控制终止的 context.Context 对象，请求携带的数据，返回给用户的数据，只不过这三要素通过多种形式进行了封装。
